name: Release

on:
    push:
        tags:
            - "v[0-9]+.*"

permissions:
    contents: write

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  prerelease: false
    release_assets:
        needs: create_release
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - build: linux-x64
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      artifact_name: "mbox-extractor-linux-amd64"
                    - build: linux-arm64
                      os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      artifact_name: "mbox-extractor-linux-arm64"
                    - build: macos-x64
                      os: macos-latest
                      target: x86_64-apple-darwin
                      artifact_name: "mbox-extractor-darwin-amd64"
                    - build: macos-arm64
                      os: macos-latest
                      target: aarch64-apple-darwin
                      artifact_name: "mbox-extractor-darwin-arm64"
                    - build: windows-x64
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      artifact_name: "mbox-extractor-windows-amd64"
                    - build: linux-musl-x64
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      artifact_name: "mbox-extractor-linux-musl-amd64"
                    # - build: freebsd-x64
                    #   os: ubuntu-latest
                    #   target: x86_64-unknown-freebsd
                    #   artifact_name: "mbox-extractor-freebsd-amd64"
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  target: ${{ matrix.target }}

            - uses: Swatinem/rust-cache@v2

            - name: Install musl-tools
              run: sudo apt update && sudo apt install -y musl-tools
              if: matrix.build == 'linux-musl-x64'

            - name: Install gcc-aarch64-linux-gnu
              run: |
                  sudo apt update
                  sudo apt install -y gcc-aarch64-linux-gnu
                  echo -e "[target.aarch64-unknown-linux-gnu]\nlinker = \"aarch64-linux-gnu-gcc\"" >> ~/.cargo/config.toml
              if: matrix.build == 'linux-arm64'

            - name: Install cross
              run: cargo install cross --git https://github.com/cross-rs/cross
              if: matrix.build == 'freebsd-x64'

            - name: Build
              run: cargo build --release --target ${{ matrix.target }}
              if: matrix.build != 'freebsd-x64'

            - name: Build (FreeBSD)
              run: cross build --release --target ${{ matrix.target }}
              if: matrix.build == 'freebsd-x64'

            - name: Upload to Release
              uses: svenstaro/upload-release-action@v2
              if: matrix.os != 'windows-latest'
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/${{ matrix.target }}/release/mbox-extractor
                  asset_name: ${{ matrix.artifact_name }}
                  tag: ${{ github.ref }}

            - name: Upload to Release (Windows)
              uses: svenstaro/upload-release-action@v2
              if: matrix.os == 'windows-latest'
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/${{ matrix.target }}/release/mbox-extractor.exe
                  asset_name: ${{ matrix.artifact_name }}.exe
                  tag: ${{ github.ref }}
